theme: jekyll-theme-cayman
description: "This page about geospactial africa"
show_downloads: true
google_analytics:

email: "team@geospatial.org"

navigation:
- text: HOME
  url: /
- text: ABOUT
  url: /about.html
- text: ORGANIZERS
  url: /organizers.html
