theme: jekyll-theme-cayman
title: "Geo Spatial Africa"

description: "This page about geospactial africa"
basepath: "geoafrica/"
google_analytics: UA-156425047-1

email: "team@geospatial.org"

navigation:
- text: HOME
  url: /
- text: ABOUT
  url: /about
- text: ORGANIZERS
  url: /organizers.html
